version: "{build}"

image: Visual Studio 2017
platform:
  - x64

environment:
  nodejs_version: "15"

cache:
  - node_modules
  
artifacts:
- path: '**\keytar-v7.0.0-electron-v85-win32-x64.tar.gz'
  name: Prebuilds

branches:
  only:
    - /master|^v\d+\.\d+\.\d+?(-\S*)?$/

clone_depth: 10

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  - npm install

build_script:
  - npm test
  - npm run prebuild-electron

test: off
deploy: off
